#ifndef INTERRUPTCONTROLLER_HPP
#define INTERRUPTCONTROLLER_HPP
#include <stdio.h>
void InterruptAttach(void (**handler)(), void (*CallBack)());
void InterruptDetach(void (**handler)(), void (*CallBack)());

extern void (*SysTick_Handler_CallBack)();
//extern void (*WWDG_IRQHandler_CallBack)();
//extern void (*PVD_IRQHandler_CallBack)();                                      
//extern void (*TAMP_STAMP_IRQHandler_CallBack)();                  
//extern void (*RTC_WKUP_IRQHandler_CallBack)();                                
//extern void (*FLASH_IRQHandler_CallBack)();                                                       
//extern void (*RCC_IRQHandler_CallBack)();                                                            
//extern void (*EXTI0_IRQHandler_CallBack)();                                                          
//extern void (*EXTI1_IRQHandler_CallBack)();                                                           
//extern void (*EXTI2_IRQHandler_CallBack)();                                                          
//extern void (*EXTI3_IRQHandler_CallBack)();                                                         
//extern void (*EXTI4_IRQHandler_CallBack)();                                                          
//extern void (*DMA1_Stream0_IRQHandler_CallBack)();                                       
//extern void (*DMA1_Stream1_IRQHandler_CallBack)();                                          
//extern void (*DMA1_Stream2_IRQHandler_CallBack)();                                          
//extern void (*DMA1_Stream3_IRQHandler_CallBack)();                                          
//extern void (*DMA1_Stream4_IRQHandler_CallBack)();                                          
//extern void (*DMA1_Stream5_IRQHandler_CallBack)();                                          
//extern void (*DMA1_Stream6_IRQHandler_CallBack)();                                          
//extern void (*ADC_IRQHandler_CallBack)();                                         
//extern void (*CAN1_TX_IRQHandler_CallBack)();                                                            
//extern void (*CAN1_RX0_IRQHandler_CallBack)();                                                          
//extern void (*CAN1_RX1_IRQHandler_CallBack)();                                                           
//extern void (*CAN1_SCE_IRQHandler_CallBack)();                                                           
//extern void (*EXTI9_5_IRQHandler_CallBack)();                                                
//extern void (*TIM1_BRK_TIM9_IRQHandler_CallBack)();                        
//extern void (*TIM1_UP_TIM10_IRQHandler_CallBack)();                      
//extern void (*TIM1_TRG_COM_TIM11_IRQHandler_CallBack)();  
//extern void (*TIM1_CC_IRQHandler_CallBack)();                                               
//extern void (*TIM2_IRQHandler_CallBack)();                                                           
//extern void (*TIM3_IRQHandler_CallBack)();                                                           
//extern void (*TIM4_IRQHandler_CallBack)();                                                           
//extern void (*I2C1_EV_IRQHandler_CallBack)();                                                         
//extern void (*I2C1_ER_IRQHandler_CallBack)();                                                         
//extern void (*I2C2_EV_IRQHandler_CallBack)();                                                        
//extern void (*I2C2_ER_IRQHandler_CallBack)();                                                           
//extern void (*SPI1_IRQHandler_CallBack)();                                                          
//extern void (*SPI2_IRQHandler_CallBack)();                                                           
//extern void (*USART1_IRQHandler_CallBack)();                                                       
//extern void (*USART2_IRQHandler_CallBack)();                                                       
//extern void (*USART3_IRQHandler_CallBack)();                                                      
//extern void (*EXTI15_10_IRQHandler_CallBack)();                                            
//extern void (*RTC_Alarm_IRQHandler_CallBack)();                            
//extern void (*OTG_FS_WKUP_IRQHandler_CallBack)();                                
//extern void (*TIM8_BRK_TIM12_IRQHandler_CallBack)();                      
//extern void (*TIM8_UP_TIM13_IRQHandler_CallBack)();                       
//extern void (*TIM8_TRG_COM_TIM14_IRQHandler_CallBack)();  
//extern void (*TIM8_CC_IRQHandler_CallBack)();                                               
//extern void (*DMA1_Stream7_IRQHandler_CallBack)();                                                 
//extern void (*FMC_IRQHandler_CallBack)();                                                            
//extern void (*SDIO_IRQHandler_CallBack)();                                                            
//extern void (*TIM5_IRQHandler_CallBack)();                                                            
//extern void (*SPI3_IRQHandler_CallBack)();                                                            
//extern void (*UART4_IRQHandler_CallBack)();                                                          
//extern void (*UART5_IRQHandler_CallBack)();                                                          
//extern void (*TIM6_DAC_IRQHandler_CallBack)();                            
//extern void (*TIM7_IRQHandler_CallBack)();                              
//extern void (*DMA2_Stream0_IRQHandler_CallBack)();                                         
//extern void (*DMA2_Stream1_IRQHandler_CallBack)();                                          
//extern void (*DMA2_Stream2_IRQHandler_CallBack)();                                           
//extern void (*DMA2_Stream3_IRQHandler_CallBack)();                                           
//extern void (*DMA2_Stream4_IRQHandler_CallBack)();                                        
//extern void (*ETH_IRQHandler_CallBack)();                                                         
//extern void (*ETH_WKUP_IRQHandler_CallBack)();                                
//extern void (*CAN2_TX_IRQHandler_CallBack)();                                                           
//extern void (*CAN2_RX0_IRQHandler_CallBack)();                                                          
//extern void (*CAN2_RX1_IRQHandler_CallBack)();                                                          
//extern void (*CAN2_SCE_IRQHandler_CallBack)();                                                          
//extern void (*OTG_FS_IRQHandler_CallBack)();                                                    
//extern void (*DMA2_Stream5_IRQHandler_CallBack)();                                          
//extern void (*DMA2_Stream6_IRQHandler_CallBack)();                                          
//extern void (*DMA2_Stream7_IRQHandler_CallBack)();                                          
//extern void (*USART6_IRQHandler_CallBack)();                                                        
//extern void (*I2C3_EV_IRQHandler_CallBack)();                                                          
//extern void (*I2C3_ER_IRQHandler_CallBack)();                                                          
//extern void (*OTG_HS_EP1_OUT_IRQHandler_CallBack)();                           
//extern void (*OTG_HS_EP1_IN_IRQHandler_CallBack)();                            
//extern void (*OTG_HS_WKUP_IRQHandler_CallBack)();                                
//extern void (*OTG_HS_IRQHandler_CallBack)();                                                   
//extern void (*DCMI_IRQHandler_CallBack)();                                                                                                             
//extern void (*HASH_RNG_IRQHandler_CallBack)();
//extern void (*FPU_IRQHandler_CallBack)();      

extern "C" void SysTick_Handler();
//extern "C" void WWDG_IRQHandler();
//extern "C" void PVD_IRQHandler();                                      
//extern "C" void TAMP_STAMP_IRQHandler();                  
//extern "C" void RTC_WKUP_IRQHandler();                                
//extern "C" void FLASH_IRQHandler();                                                       
//extern "C" void RCC_IRQHandler();                                                            
//extern "C" void EXTI0_IRQHandler();                                                          
//extern "C" void EXTI1_IRQHandler();                                                           
//extern "C" void EXTI2_IRQHandler();                                                          
//extern "C" void EXTI3_IRQHandler();                                                         
//extern "C" void EXTI4_IRQHandler();                                                          
//extern "C" void DMA1_Stream0_IRQHandler();                                       
//extern "C" void DMA1_Stream1_IRQHandler();                                          
//extern "C" void DMA1_Stream2_IRQHandler();                                          
//extern "C" void DMA1_Stream3_IRQHandler();                                          
//extern "C" void DMA1_Stream4_IRQHandler();                                          
//extern "C" void DMA1_Stream5_IRQHandler();                                          
//extern "C" void DMA1_Stream6_IRQHandler();                                          
//extern "C" void ADC_IRQHandler();                                         
//extern "C" void CAN1_TX_IRQHandler();                                                            
//extern "C" void CAN1_RX0_IRQHandler();                                                          
//extern "C" void CAN1_RX1_IRQHandler();                                                           
//extern "C" void CAN1_SCE_IRQHandler();                                                           
//extern "C" void EXTI9_5_IRQHandler();                                                
//extern "C" void TIM1_BRK_TIM9_IRQHandler();                        
//extern "C" void TIM1_UP_TIM10_IRQHandler();                      
//extern "C" void TIM1_TRG_COM_TIM11_IRQHandler();  
//extern "C" void TIM1_CC_IRQHandler();                                               
//extern "C" void TIM2_IRQHandler();                                                           
//extern "C" void TIM3_IRQHandler();                                                           
//extern "C" void TIM4_IRQHandler();                                                           
//extern "C" void I2C1_EV_IRQHandler();                                                         
//extern "C" void I2C1_ER_IRQHandler();                                                         
//extern "C" void I2C2_EV_IRQHandler();                                                        
//extern "C" void I2C2_ER_IRQHandler();                                                           
//extern "C" void SPI1_IRQHandler();                                                          
//extern "C" void SPI2_IRQHandler();                                                           
//extern "C" void USART1_IRQHandler();                                                       
//extern "C" void USART2_IRQHandler();                                                       
//extern "C" void USART3_IRQHandler();                                                      
//extern "C" void EXTI15_10_IRQHandler();                                            
//extern "C" void RTC_Alarm_IRQHandler();                            
//extern "C" void OTG_FS_WKUP_IRQHandler();                                
//extern "C" void TIM8_BRK_TIM12_IRQHandler();                      
//extern "C" void TIM8_UP_TIM13_IRQHandler();                       
//extern "C" void TIM8_TRG_COM_TIM14_IRQHandler();  
//extern "C" void TIM8_CC_IRQHandler();                                               
//extern "C" void DMA1_Stream7_IRQHandler();                                                 
//extern "C" void FMC_IRQHandler();                                                            
//extern "C" void SDIO_IRQHandler();                                                            
//extern "C" void TIM5_IRQHandler();                                                            
//extern "C" void SPI3_IRQHandler();                                                            
//extern "C" void UART4_IRQHandler();                                                          
//extern "C" void UART5_IRQHandler();                                                          
//extern "C" void TIM6_DAC_IRQHandler();                            
//extern "C" void TIM7_IRQHandler();                              
//extern "C" void DMA2_Stream0_IRQHandler();                                         
//extern "C" void DMA2_Stream1_IRQHandler();                                          
//extern "C" void DMA2_Stream2_IRQHandler();                                           
//extern "C" void DMA2_Stream3_IRQHandler();                                           
//extern "C" void DMA2_Stream4_IRQHandler();                                        
//extern "C" void ETH_IRQHandler();                                                         
//extern "C" void ETH_WKUP_IRQHandler();                                
//extern "C" void CAN2_TX_IRQHandler();                                                           
//extern "C" void CAN2_RX0_IRQHandler();                                                          
//extern "C" void CAN2_RX1_IRQHandler();                                                          
//extern "C" void CAN2_SCE_IRQHandler();                                                          
//extern "C" void OTG_FS_IRQHandler();                                                    
//extern "C" void DMA2_Stream5_IRQHandler();                                          
//extern "C" void DMA2_Stream6_IRQHandler();                                          
//extern "C" void DMA2_Stream7_IRQHandler();                                          
//extern "C" void USART6_IRQHandler();                                                        
//extern "C" void I2C3_EV_IRQHandler();                                                          
//extern "C" void I2C3_ER_IRQHandler();                                                          
//extern "C" void OTG_HS_EP1_OUT_IRQHandler();                           
//extern "C" void OTG_HS_EP1_IN_IRQHandler();                            
//extern "C" void OTG_HS_WKUP_IRQHandler();                                
//extern "C" void OTG_HS_IRQHandler();                                                   
//extern "C" void DCMI_IRQHandler();                                                                                                             
//extern "C" void HASH_RNG_IRQHandler();
//extern "C" void FPU_IRQHandler();      



#endif